In [2]:
i =1
a = 'asd %d',i
a

('asd %d', 1)

In [2]:
import numpy as np
from gym import spaces

In [3]:
scan_space = spaces.Box(low=0., high=4., shape=(512, ))
image_space = spaces.Box(low=0., high=4., shape=(640,480,3))

In [5]:
print(image_space)
print(scan_space)

Box(640, 480, 3)
Box(512,)


In [6]:
class RunningStat(object):
    def __init__(self, shape):
        self._size = 0
        self._mean, self._std = np.zeros(shape), np.zeros(shape)

    def add(self, x):
        x = np.asarray(x)
        assert x.shape == self._mean.shape

        self._size += 1
        if self._size == 1:
            self._mean = x
        else:
            self._mean_old = self._mean.copy()
            self._mean = self._mean_old + (x - self._mean_old) / self._size
            self._std = self._std + (x - self._mean_old) * (x - self._mean)

    @property
    def size(self):
        return self._size

    @property
    def mean(self):
        return self._mean

    @property
    def var(self):
        return self._std / (self._size - 1) if self._size > 1 else self._std

    @property
    def std(self):
        return np.sqrt(self.var)

    @property
    def shape(self):
        return self._mean.shape

In [9]:
rs_scan = RunningStat(scan_space.shape[0])
rs_cam = RunningStat(image_space.shape)
print(scan_space.shape[0])
print(image_space.shape)
print(rs_scan)
print(rs_cam)

512
(640, 480, 3)


In [ ]:
np.ones()

In [15]:
pixel = 640*480*3
scan = np.stack(([1]*512,[0]*512,[2]*512),axis=1)
image= np.stack(([1]*pixel,[2]*pixel,[0]*pixel,
                 [4]*pixel,[3]*pixel),axis=1)
scanbatch = np.array(scan)
imagebatch= np.array(image)
print(scanbatch)
print(imagebatch)

[[1 0 2]
 [1 0 2]
 [1 0 2]
 ...
 [1 0 2]
 [1 0 2]
 [1 0 2]]
[[1 2 0 4 3]
 [1 2 0 4 3]
 [1 2 0 4 3]
 ...
 [1 2 0 4 3]
 [1 2 0 4 3]
 [1 2 0 4 3]]


In [8]:
import sysv_ipc
import copy
import math
import random
import StringIO
import struct
import time
import csv

key=42
semaphore = sysv_ipc.Semaphore(key, 0)
memory = sysv_ipc.SharedMemory(key, 0)
received_data_size = 0

In [9]:
semaphore.acquire()
size = memory.read(byte_count=4)
length, = struct.unpack("i", size)

KeyboardInterrupt: 